### ISSUE TITLE
cg-mwesplit splits too much in nob grc

### ISSUE THREAD

**Issue by Trondtr** [GrammarSoft/cg3#108]
This issue reports unwanted behaviour from cg-mwesplit (for some unknown reason).

Background:
Setting: lang-nob grammarchecker in giellalt.

We want: *kjærlighetsforhold* as a compound with lemma `...forhold`. This we get for mode `dev2` but not for `dev3`:

```
uit-mac-443:grammarcheckers ttr000$ e kjærlighetsforhold|sh modes/trace-nobgram-dev2-cg.mode 
"<kjærlighetsforhold>"
	"forhold" N Neu Pl Indef <W:0.0> "<forhold>"
		"kjærlighet" N Cmp/s Cmp <W:0.0> "<kjærlighets>"
	"forhold" N Neu Sg Indef <W:0.0> "<forhold>"
		"kjærlighet" N Cmp/s Cmp <W:0.0> "<kjærlighets>"
:\n
uit-mac-443:grammarcheckers ttr000$ e kjærlighetsforhold|sh modes/trace-nobgram-dev3-mwe-split.mode 
"<kjærlighets>"
	"kjærlighet" N Cmp/s Cmp <W:0.0>  <========== **The error is introduced here**
"<forhold>"
	"forhold" N Neu Pl Indef <W:0.0>
	"forhold" N Neu Sg Indef <W:0.0>
:\n
```

The difference between *dev2* and *dev3* is that the latter adds `cg-mwesplit`.

Now, `tokenisers/mwe-dis.cg3` did not have `Cmp/s` and the other nob compound tags declared (fixed now), but I cannot see how it affects the behaviour of cg-mwesplit, and I also cannot see from the code (https://github.com/GrammarSoft/cg3/blob/main/src/cg-mwesplit.cpp) how this happens. 

But it does. 

Comments, @unhammer ?

**Comment by snomos** [comment]
> I thought giella-analysers typically kept them as a single main reading

That requires the compound to be lexicalised.

Dynamic compounds should normally *not* be split, as we want one compound to be one cohort, with the final element in the compound bearing the main reading (and non-final elements thus as sub-readings, thus avoiding that they interfere with disambiguation in later stages).

> The subreadings and word form tags are printed by hfst-tokenise whenever there is a `ɛ:@PMATCH_INPUT_MARK@` (typically at the compound border) in the lexicon.

So what you are saying is that there must be a pair `ɛ:@PMATCH_INPUT_MARK@` at the word boundary, and by removing that the problem should go away?

> The subreading+wordform tag structure in libdivvun grammar checking was meant for mwe's that might be ambiguous with single-token readings, e.g. `17.` (`"17" adj ord` vs `"17" num` + `"." punct`).

It might have been the starting point, but it is useful in every context where the tokenisation is ambiguous. That might include compounds (ie when written as two words), but is usually not. It is for example useful to distinguish between the three different analysis of `god fot`, as in:

- han har ein god fot, og ein dårleg (god adj + fot n)
- han står på god fot med naboen (`på god fot adv`, fixed expression)
- han er ute med god foten (e.g. when dancing, football, as a misspelling of `godfoten`)

**Comment by Trondtr** [comment]
So, we do not want to produce the final token `"<kjærlighets>`, in
`"kjærlighet" N Cmp/s Cmp <W:0.0> "<kjærlighets>"`
is that it?

- How is it produced?
- How can we prevent it from being produced?

The background here is that I want a gtc rule to protest against *en kjærlighetsforhold* (agains `en+Det+Msc ...forhold+N+Sg+Neu`) but this is blocked by the intervening "lemma" `kjærlighets`. So yes, I want `forhold` as the dynamic lemma, and (it seems) avoid putting the `"<kjærlighets>"` at the end there.

**Comment by unhammer** [comment]
giella-sme does the expected thing, if we want them to be subreadings but not split:

```sh
$ echo skuvlabusse | hfst-tokenise -g /usr/share/giella/sme/tokeniser-disamb-gt-desc.pmhfst
"<skuvlabusse>"
        "busse" N Sem/Ctain-clth_Veh Sg Acc <W:0.0>
                "skuvla" N Sem/Edu_Org Cmp/SgNom Cmp <W:0.0>
        "busse" N Sem/Ctain-clth_Veh Sg Gen <W:0.0>
                "skuvla" N Sem/Edu_Org Cmp/SgNom Cmp <W:0.0>
        "busse" N Sem/Ctain-clth_Veh Sg Gen Allegro <W:0.0>
                "skuvla" N Sem/Edu_Org Cmp/SgNom Cmp <W:0.0>
        "busse" N Sem/Ctain-clth_Veh Sg Nom <W:0.0>
                "skuvla" N Sem/Edu_Org Cmp/SgNom Cmp <W:0.0>
        "skuvlabusse" N Sem/Veh Sg Acc <W:0.0>
        "skuvlabusse" N Sem/Veh Sg Gen <W:0.0>
        "skuvlabusse" N Sem/Veh Sg Gen Allegro <W:0.0>
        "skuvlabusse" N Sem/Veh Sg Nom <W:0.0>
```
Here there are lexicalised readings as well as dynamic compounds, but no wordform-tags so cg-mwesplit leaves them alone:

```sh
$ echo skuvlabusse | hfst-tokenise -g /usr/share/giella/sme/tokeniser-disamb-gt-desc.pmhfst|grep -v '"skuvlabusse" N ' | cg-mwesplit
"<skuvlabusse>"
        "busse" N Sem/Ctain-clth_Veh Sg Acc <W:0.0>
                "skuvla" N Sem/Edu_Org Cmp/SgNom Cmp <W:0.0>
        "busse" N Sem/Ctain-clth_Veh Sg Gen <W:0.0>
                "skuvla" N Sem/Edu_Org Cmp/SgNom Cmp <W:0.0>
        "busse" N Sem/Ctain-clth_Veh Sg Gen Allegro <W:0.0>
                "skuvla" N Sem/Edu_Org Cmp/SgNom Cmp <W:0.0>
        "busse" N Sem/Ctain-clth_Veh Sg Nom <W:0.0>
                "skuvla" N Sem/Edu_Org Cmp/SgNom Cmp <W:0.0>
```

> It might have been the starting point, but it is useful in every context where the tokenisation is ambiguous. 

Sorry, that is what I meant (it's just harder to think of examples where tokenisation is ambiguous without being ambiguous with single-token readings). What I was trying to contrast it with is the initial example – where there is no ambiguous tokenisation at all.

**Comment by unhammer** [comment]
But giella-nob also does the right thing:

```
$ echo kjærlighetsforhold | hfst-tokenise -g /usr/share/giella/nob/tokeniser-gramcheck-gt-desc.pmhfst
"<kjærlighetsforhold>"
        "forhold" N Neu Pl Indef <W:0.0>
                "kjærlighet" N Cmp/s Cmp <W:0.0>
        "forhold" N Neu Sg Indef <W:0.0>
                "kjærlighet" N Cmp/s Cmp <W:0.0>
```

So where are these wordform-tags coming from?

**Comment by unhammer** [comment]
```sh
$ sudo apt install -y giella-nob
$ unzip /usr/share/voikko/4/nb.zcheck
$ divvun-gen-sh pipespec.xml --dir .
$ echo kjærlighetsforhold | sh trace-nobgram-dev2-cg.mode
Error: Error opening /tmp/nb/mwe-dis.cg3 for reading!
$ sed  's/\.cg3/\.bin/' trace-nobgram-dev2-cg.mode  > trace-nobgram-dev2-bin.mode
$ echo kjærlighetsforhold | sh trace-nobgram-dev2-bin.mode
"<kjærlighetsforhold>"
        "forhold" N Neu Pl Indef <W:0.0>
                "kjærlighet" N Cmp/s Cmp <W:0.0>
        "forhold" N Neu Sg Indef <W:0.0>
                "kjærlighet" N Cmp/s Cmp <W:0.0>
:\n

```

**Comment by Trondtr** [comment]
I am not able to replicate this on my machine, I still get the mwe split.

**Comment by flammie** [comment]
could it be an old version thing? I didn't know we had overloaded the meaning of surface form analysis in mwe's so I used it for phonemising mwe's but it's been since reverted

**Comment by unhammer** [comment]
It seems my giella-nob is from May
```
$ apt-cache show giella-nob
Package: giella-nob
Version: 0.2.0+g2086~0fb7e536-1~sid1
```
(this https://github.com/giellalt/lang-nob/commit/0fb7e536 but that commit is gone, possibly corresponds to https://github.com/giellalt/lang-nob/commit/3ec19f9669343829a1815d2d59f2ad434b237c17 – guess the branch must've had a rebase since the latest build)

@Trondtr do you get wordform-tags on your readings from `$ echo kjærlighetsforhold | sh trace-nobgram-dev0-morph.mode ` ?

**Comment by unhammer** [comment]
And can you send me the nob tokeniser-gramcheck-gt-desc.pmhfst so I can verify it's the data and not tools?

**Comment by Trondtr** [comment]
Yes.

``` 
uit-mac-443:grammarcheckers ttr000$ echo kjærlighetsforhold | sh modes/trace-nobgram-dev0-morph.mode
"<kjærlighetsforhold>"
	"forhold" N Neu Pl Indef <W:0.0> "<forhold>"
		"kjærlighet" N Cmp/s Cmp <W:0.0> "<kjærlighets>"
	"forhold" N Neu Sg Indef <W:0.0> "<forhold>"
		"kjærlighet" N Cmp/s Cmp <W:0.0> "<kjærlighets>"

**Comment by Trondtr** [comment]
Kevin: Fila ligg på heimeområdet mitt på gtweb (verken github eller e-postprogrammet likte fila). ... men .gz ser ut til å fungere, så no kjem fila her og.
[tokeniser-gramcheck-gt-desc.pmhfst.tar.gz](https://github.com/GrammarSoft/cg3/files/10184627/tokeniser-gramcheck-gt-desc.pmhfst.tar.gz)

**Comment by unhammer** [comment]
```
$ echo kjærlighetsforhold | hfst-tokenize -g tokeniser-gramcheck-gt-desc.pmhfst 
"<kjærlighetsforhold>"
        "forhold" N Neu Pl Indef <W:0.0>
                "kjærlighet" N Cmp/s Cmp <W:0.0>
        "forhold" N Neu Sg Indef <W:0.0>
                "kjærlighet" N Cmp/s Cmp <W:0.0>
```
@Trondtr får du `… "<kjærlighets>"` etc. eller får du det eg får med den kommandoen?

**Comment by TinoDidriksen** [comment]
giella-nob fails to build from scratch, which is probably why it's so old:
```
make[3]: Entering directory '/build/giella-nob-0.2.0+g2231~8e3882e5-1~sid1/src/fst'
...
Compiling... *** ERROR: could not parse lexc file: treating warnings as errors [--Werror] ***
/usr/bin/hfst-lexc: The file lexicon.tmp.lexc did not compile cleanly.
(if there are no error messages above, try -v or -d to get more info)
make[3]: *** [Makefile:1197: lexicon.tmp.hfst] Error 1
```

**Comment by Trondtr** [comment]
@unhammer 
``` 
uit-mac-443:tokenisers ttr000$ echo kjærlighetsforhold | hfst-tokenize -g tokeniser-gramcheck-gt-desc.pmhfst
"<kjærlighetsforhold>"
	"forhold" N Neu Pl Indef <W:0.0> "<forhold>"
		"kjærlighet" N Cmp/s Cmp <W:0.0> "<kjærlighets>"
	"forhold" N Neu Sg Indef <W:0.0> "<forhold>"
		"kjærlighet" N Cmp/s Cmp <W:0.0> "<kjærlighets>"
``` 

Given Tino's result I guess we now have the same result, hopefully (!) also the same bug.

**Comment by snomos** [comment]
> could it be an old version thing? I didn't know we had overloaded the meaning of surface form analysis in mwe's so I used it for phonemising mwe's but it's been since reverted

@Trondtr could you make sure you have the latest nightly installed?

**Comment by snomos** [comment]
I get the same analysis as Kevin:

```sh
 echo kjærlighetsforhold | hfst-tokenize -g tools/tokenisers/tokeniser-gramcheck-gt-desc.pmhfst 
"<kjærlighetsforhold>"
	"forhold" N Neu Pl Indef <W:0.0>
		"kjærlighet" N Cmp/s Cmp <W:0.0>
	"forhold" N Neu Sg Indef <W:0.0>
		"kjærlighet" N Cmp/s Cmp <W:0.0>
```

= this might be local to @Trondtr ?

**Comment by Trondtr** [comment]
Yes, it seems so (local to me in 2022). Now I get (with the pmhfst from sept 5th):

```
"<kjærlighetsforhold>"
	"forhold" N Neu Pl Indef <W:0.0>
		"kjærlighet" N Cmp/s Cmp <W:0.0>
	"forhold" N Neu Sg Indef <W:0.0>
		"kjærlighet" N Cmp/s Cmp <W:0.0>
```

And yes, now the correction works:

```
uit-mac-443:grammarcheckers ttr000$ e En kjærlighetsforhold har vart lenge. | divvun-checker -a nb.zcheck 
{"errs":[["En",0,2,"msyn-agr-detmsc-detneu","Når en determinativ, som her \"En\", modifiserer et intetkjønnssubstantiv, som her \"kjærlighetsforhold\", skal det stå i intetkjønn",["Et"],"Samsvar i kjønn i substantivfraser"]],"text":"En kjærlighetsforhold har vart lenge."}


uit-mac-443:grammarcheckers ttr000$ e En kjærlighetsforhold har vart lenge. | sh modes/trace-nobgram.mode 
"<En>"
	"en" Det Dem Fem Sg <W:0.0> ID:1 R:$2:2
	"en" Det Dem Msc Sg <W:0.0> &msyn-agr-detmsc-detneu ID:1 R:$2:2 ADD:660:msyn-agr-detmsc-detneu COPY:675:msyn-agr-detmsc-detneu
msyn-agr-detmsc-detneu
	"et" Det Dem <W:0.0> Neu Sg &msyn-agr-detmsc-detneu &SUGGEST ID:1 R:$2:2 ADD:660:msyn-agr-detmsc-detneu COPY:675:msyn-agr-detmsc-detneu
et+Det+Dem+Neu+Sg	Et
	"en" Pron Indef Fem Sg <W:0.0> ID:1 R:$2:2
	"en" Pron Indef Msc Sg <W:0.0> &msyn-agr-detmsc-detneu ID:1 R:$2:2 ADD:668:msyn-agr-detmsc-detneu COPY:675:msyn-agr-detmsc-detneu
msyn-agr-detmsc-detneu
	"et" Pron Indef <W:0.0> Neu Sg &msyn-agr-detmsc-detneu &SUGGEST ID:1 R:$2:2 ADD:668:msyn-agr-detmsc-detneu COPY:675:msyn-agr-detmsc-detneu
et+Pron+Indef+Neu+Sg	Et
;	"ene" V Imp <W:0.0> REMOVE:14331
: 
"<kjærlighetsforhold>"
	"forhold" N Neu Sg Indef <W:0.0> ID:2 ADDRELATION($2):677:msyn-agr-detmsc-detneu
		"kjærlighet" N Cmp/s Cmp <W:0.0> ID:2
;	"forhold" N Neu Pl Indef <W:0.0> REMOVE:18336
;		"kjærlighet" N Cmp/s Cmp <W:0.0>
:

**Comment by Trondtr** [comment]
We may thus close.
