### ISSUE TITLE
MergeCohorts reuse and wipe data

### ISSUE THREAD

**Issue by TinoDidriksen** [GrammarSoft/cg3#122]
`<Unhammer> Ideally, I would be able to do something like MERGECOHORTS ("<$1$_1$3>"v "$2 $4"v np) where $_1 (or whatever) is the non-cg-data that was after the first cohort, and then that non-cg-data is set to empty string so it's not output twice `

**Comment by unhammer** [comment]
Possible strategy: For every space in the rule word form (before varstringifying), we can delete one space from the text after each of the withs. So if the rule is `MERGECOHORTS ("<$1 $2 $3>"v *) ("<(.*)>"r) WITH  (1 ("<(.*)>"r)) (2 ("<(.*)>"r));` and input is `^a/a<n>$ -  `^b/b<n>$ - `^c/c<n>$` we should get `--^a b c/a<n>$`. 

```c++
			getTagList(*rule->maplist, theTags); 
auto rulewf = findWf(theTags)
while(rulewf.find(32)) dropspaces++

[A FEW MOMENTS LATER]

				for (auto c : withs) {
                                      while(dropspaces && c.text.find(32)) { c.text.deleteASpace(); dropspaces--; }
                                      rem_cohort(c);
                               }
```
