### ISSUE TITLE
`cg-comp` hangs on misspelled rules inside `WITH`

### ISSUE THREAD

**Issue by mr-martian** [GrammarSoft/cg3#144]
```
WITH (@obl) IF (cll (Conj3Pp)) {
  SUBSTITITE (@obl) (@conj) (*) ;
} ;
```
Note `SUBSTITITE` rather than `SUBSTITUTE`.

**Comment by TinoDidriksen** [comment]
Because https://github.com/GrammarSoft/cg3/blob/main/src/TextualParser.cpp#L1577 returns false, but nothing handles that. Is it intended that `maybeParseRule()` can fail here and maybe succeed after `SKIPWS()`?

**Comment by mr-martian** [comment]
I think that's probably just a mistake on my part and it should error there.
