### ISSUE TITLE
SetParent with named relations

### ISSUE THREAD

**Issue by TinoDidriksen** [GrammarSoft/cg3#45]
Allow SetParent/Child to simultaneously set named relations between (to and/or from) the affected cohorts.

Similar to https://github.com/TinoDidriksen/cg3/issues/34

**Comment by mr-martian** [comment]
Perhaps something like this?

```
MAP @nmod:poss (prn) IF (-1 (subs)) ;
SETPARENT (prn @nmod:poss) TO (-1 (subs)) ;

=>

SETPARENT (prn) TO (-1 (subs)) AS @nmod:poss ;
```
