### ISSUE TITLE
Fix bitrotted --optimize-(un)safe

### ISSUE THREAD

**Issue by TinoDidriksen** [GrammarSoft/cg3#63]
Seems `--optimize-safe` and `-unsafe` have bitrotted.

**Comment by unhammer** [comment]
- doesn't include template definitions
- `APPEND ("$1"v tag)` turns into `APPEND S42` which gives `Error: There must be a baseform before any other tags in APPEND on line 5862`

**Comment by TinoDidriksen** [comment]
Optimization entirely removed in https://github.com/GrammarSoft/cg3/commit/af16348a4428ef2ec3e403d198b5c8adcfdf876f in favour of vastly better profiling information that other tools can build on.
