### ISSUE TITLE
error while loading shared libraries: libcg3.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Simon-Bakken-Jantasuk** [GrammarSoft/cg3#94]
"error while loading shared libraries: libcg3.so.1: cannot open shared object file: No such file or directory" 
what I did:
./cmake.sh
make -j3
sudo make install
 I got no errors from Installing it in this way. Calling vislcg3 creates the error, so other programs that need viscg3. Like cp-proc and etc.

Output:
./cmake.sh
` - rm -rf CMake caches
- cmake  .
-- The CXX compiler identification is GNU 11.2.0
-- The C compiler identification is GNU 11.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test COMPILER_SUPPORTS_Wnounusedresult
-- Performing Test COMPILER_SUPPORTS_Wnounusedresult - Success
-- Performing Test COMPILER_SUPPORTS_flto
-- Performing Test COMPILER_SUPPORTS_flto - Success
-- Performing Test COMPILER_SUPPORTS_stdc2x
-- Performing Test COMPILER_SUPPORTS_stdc2x - Success
-- Performing Test COMPILER_SUPPORTS_-std-c--23
-- Performing Test COMPILER_SUPPORTS_-std-c--23 - Success
-- Looking for C++ include string_view
-- Looking for C++ include string_view - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Did not find Boost locally; trying globally...
-- If this doesn't work, run ./get-boost.sh and try again.
-- Found Boost: /usr/lib64/cmake/Boost-1.78.0/BoostConfig.cmake (found suitable version "1.78.0", minimum required is "1.53.0")
-- Found ICU header files in /usr/include
-- Found ICU libraries: /usr/lib/libicuuc.so
-- Found ICU version 70.1
-- Found tcmalloc: /usr/lib/libtcmalloc.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/archlinux/cg3
- You may now perform: make -j3 `
make -j3
`[  1%] Building CXX object src/CMakeFiles/cg3.dir/BinaryGrammar.cpp.o
[  5%] Building CXX object src/CMakeFiles/cg3.dir/BinaryGrammar_read.cpp.o
[  5%] Building CXX object src/CMakeFiles/cg3.dir/libcg3.cpp.o
[  7%] Building CXX object src/CMakeFiles/cg3.dir/BinaryGrammar_read_10043.cpp.o
[  9%] Building CXX object src/CMakeFiles/cg3.dir/BinaryGrammar_write.cpp.o
[ 11%] Building CXX object src/CMakeFiles/cg3.dir/Cohort.cpp.o
[ 13%] Building CXX object src/CMakeFiles/cg3.dir/CohortIterator.cpp.o
[ 15%] Building CXX object src/CMakeFiles/cg3.dir/ContextualTest.cpp.o
[ 17%] Building CXX object src/CMakeFiles/cg3.dir/Grammar.cpp.o
[ 19%] Building CXX object src/CMakeFiles/cg3.dir/GrammarApplicator.cpp.o
[ 21%] Building CXX object src/CMakeFiles/cg3.dir/GrammarApplicator_matchSet.cpp.o
[ 23%] Building CXX object src/CMakeFiles/cg3.dir/GrammarApplicator_reflow.cpp.o
[ 25%] Building CXX object src/CMakeFiles/cg3.dir/GrammarApplicator_runContextualTest.cpp.o
[ 27%] Building CXX object src/CMakeFiles/cg3.dir/GrammarApplicator_runGrammar.cpp.o
[ 29%] Building CXX object src/CMakeFiles/cg3.dir/GrammarApplicator_runRules.cpp.o
[ 31%] Building CXX object src/CMakeFiles/cg3.dir/GrammarWriter.cpp.o
[ 33%] Building CXX object src/CMakeFiles/cg3.dir/Relabeller.cpp.o
[ 35%] Building CXX object src/CMakeFiles/cg3.dir/MweSplitApplicator.cpp.o
[ 37%] Building CXX object src/CMakeFiles/cg3.dir/Reading.cpp.o
[ 39%] Building CXX object src/CMakeFiles/cg3.dir/Rule.cpp.o
[ 41%] Building CXX object src/CMakeFiles/cg3.dir/Set.cpp.o
[ 43%] Building CXX object src/CMakeFiles/cg3.dir/SingleWindow.cpp.o
[ 45%] Building CXX object src/CMakeFiles/cg3.dir/Strings.cpp.o
[ 47%] Building CXX object src/CMakeFiles/cg3.dir/Tag.cpp.o
[ 49%] Building CXX object src/CMakeFiles/cg3.dir/TextualParser.cpp.o
[ 50%] Building CXX object src/CMakeFiles/cg3.dir/Window.cpp.o
[ 52%] Building CXX object src/CMakeFiles/cg3.dir/uextras.cpp.o
[ 54%] Building CXX object src/CMakeFiles/cg3.dir/__/include/posix/popen_plus.cpp.o
[ 56%] Linking CXX shared library libcg3.so
[ 56%] Built target cg3
[ 58%] Building CXX object src/CMakeFiles/cg-relabel.dir/cg-relabel.cpp.o
[ 60%] Building CXX object src/CMakeFiles/cg-comp.dir/cg_comp.cpp.o
[ 62%] Building CXX object src/CMakeFiles/cg-proc.dir/cg_proc.cpp.o
[ 64%] Linking CXX executable cg-relabel
[ 64%] Built target cg-relabel
[ 66%] Building CXX object src/CMakeFiles/cg-conv.dir/cg_conv.cpp.o
[ 68%] Linking CXX executable cg-comp
[ 68%] Built target cg-comp
[ 70%] Building CXX object src/CMakeFiles/cg-mwesplit.dir/cg-mwesplit.cpp.o
[ 72%] Building CXX object src/CMakeFiles/cg-proc.dir/ApertiumApplicator.cpp.o
[ 74%] Building CXX object src/CMakeFiles/cg-conv.dir/ApertiumApplicator.cpp.o
[ 76%] Linking CXX executable cg-mwesplit
[ 76%] Built target cg-mwesplit
[ 78%] Building CXX object src/CMakeFiles/cg-conv.dir/MatxinApplicator.cpp.o
[ 80%] Building CXX object src/CMakeFiles/cg-proc.dir/MatxinApplicator.cpp.o
[ 82%] Building CXX object src/CMakeFiles/cg-conv.dir/FormatConverter.cpp.o
[ 84%] Building CXX object src/CMakeFiles/cg-conv.dir/FSTApplicator.cpp.o
[ 86%] Building CXX object src/CMakeFiles/cg-conv.dir/NicelineApplicator.cpp.o
[ 88%] Linking CXX executable cg-proc
[ 90%] Building CXX object src/CMakeFiles/cg-conv.dir/PlaintextApplicator.cpp.o
[ 92%] Building CXX object src/CMakeFiles/vislcg3.dir/main.cpp.o
[ 92%] Built target cg-proc
[ 94%] Building C object src/CMakeFiles/test_libcg3.dir/test_libcg3.c.o
[ 96%] Linking C executable test_libcg3
[ 96%] Built target test_libcg3
[ 98%] Linking CXX executable cg-conv
[100%] Linking CXX executable vislcg3
[100%] Built target vislcg3
[100%] Built target cg-conv`
sudo make install
`Consolidate compiler generated dependencies of target cg3
[ 56%] Built target cg3
Consolidate compiler generated dependencies of target cg-comp
[ 60%] Built target cg-comp
Consolidate compiler generated dependencies of target cg-proc
[ 68%] Built target cg-proc
Consolidate compiler generated dependencies of target cg-relabel
[ 72%] Built target cg-relabel
Consolidate compiler generated dependencies of target cg-conv
[ 88%] Built target cg-conv
Consolidate compiler generated dependencies of target cg-mwesplit
[ 92%] Built target cg-mwesplit
Consolidate compiler generated dependencies of target vislcg3
[ 96%] Built target vislcg3
Consolidate compiler generated dependencies of target test_libcg3
[100%] Built target test_libcg3
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /usr/local/lib/pkgconfig/cg3.pc
-- Up-to-date: /usr/local/share/man/man1
-- Up-to-date: /usr/local/share/man/man1/cg3-autobin.pl.1
-- Up-to-date: /usr/local/share/man/man1/cg-conv.1
-- Up-to-date: /usr/local/share/man/man1/cg-comp.1
-- Up-to-date: /usr/local/share/man/man1/cg-proc.1
-- Up-to-date: /usr/local/share/man/man1/vislcg3.1
-- Installing: /usr/local/lib/libcg3.so.1
-- Up-to-date: /usr/local/lib/libcg3.so
-- Up-to-date: /usr/local/include/cg3.h
-- Installing: /usr/local/bin/cg-comp
-- Set runtime path of "/usr/local/bin/cg-comp" to ""
-- Installing: /usr/local/bin/cg-proc
-- Set runtime path of "/usr/local/bin/cg-proc" to ""
-- Installing: /usr/local/bin/cg-relabel
-- Set runtime path of "/usr/local/bin/cg-relabel" to ""
-- Installing: /usr/local/bin/cg-mwesplit
-- Set runtime path of "/usr/local/bin/cg-mwesplit" to ""
-- Installing: /usr/local/bin/cg-conv
-- Set runtime path of "/usr/local/bin/cg-conv" to ""
-- Installing: /usr/local/bin/vislcg3
-- Set runtime path of "/usr/local/bin/vislcg3" to ""
-- Up-to-date: /usr/local/bin/cg3-autobin.pl
-- Up-to-date: /usr/local/bin/cg-sort
-- Up-to-date: /usr/local/bin/cg-strictify
-- Up-to-date: /usr/local/bin/cg-untrace
-- Up-to-date: /usr/local/share/emacs/site-lisp/cg.el`

**Comment by TinoDidriksen** [comment]
After `sudo make install` you need to run `sudo ldconfig` to update the cache of known runtime libraries.

**Comment by Simon-Bakken-Jantasuk** [comment]
`sudo ldconfig` didn't work first. But it worked after I defined this, and exported it.

 LD_LIBRARY_PATH=/usr/local/lib 
 LD_LIBRARY_PATH= LD_LIBRARY_PATH:libcg3.so.1 
export LD_LIBRARY_PATH

**Comment by TinoDidriksen** [comment]
If `ldconfig` doesn't work by itself, that means `/usr/local/lib` is not even listed in `/etc/ld.so.conf`
