### ISSUE TITLE
Python usage example

### ISSUE THREAD

**Issue by Mukhammadsaid19** [GrammarSoft/cg3#97]
Hello, everyone! I'm facing problems with making the SWIG python bindings work as I couldn't find any docs about the usage. Could you show the basic example of simulating this command in Python?

`$ vislcg3 -g <grammar> -I <input>`

Thanks in advance.

**Comment by TinoDidriksen** [comment]
The Python module was created for use by https://github.com/apertium/apertium-python and is used in https://github.com/apertium/apertium-python/blob/master/apertium/utils.py

Beyond that, I don't know of anyone that uses it. The module is rather unmaintained.

**Comment by Mukhammadsaid19** [comment]
Hello, Mr. Didriksen! Thanks for the response.

I was planning to use the constraint grammar for punctuation checking in Uzbek, coupled with the morph analyzer. As we don't have sufficient resources for creating datasets related to punctuation, we decided to follow the [paper on punctuation checking in Basque](https://www.researchgate.net/profile/Montse-Maritxalar/publication/2893071_Toward_a_punctuation_checker_for_Basque/links/00b7d51a609954a22b000000/Toward-a-punctuation-checker-for-Basque.pdf) and use it in our server (currently written in Python). So perhaps creating our bindings would work or maybe you could suggest to us other production-level solutions? Thanks in advance.

**Comment by TinoDidriksen** [comment]
I don't personally use Python for anything if I can help it. But for daemons and services where I need to use CG or other pipes, I just open (and keep open) a native process and pump data into it with a flush as delimiter and read the result. Works very well, and it insulates the main program from backend crashes.

As for Uzbek, are you aware of https://github.com/apertium/apertium-uzb and the other work by Apertium? We hang out on [IRC on OFTC channel #apertium](https://wiki.apertium.org/wiki/Contact).

**Comment by Mukhammadsaid19** [comment]
Hm, looks like we would go with this approach. Thank you for your suggestion.

I'm aware of Apertium, we are planning to contribute to it as soon as we go open-source :D
